// <auto-generated />
using System;
using BicycleRental.Infrastructure.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BicycleRental.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(BicycleRentalDbContext))]
    partial class BicycleRentalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BicycleRental.Domain.Models.Bicycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("color");

                    b.Property<int>("ModelId")
                        .HasColumnType("int")
                        .HasColumnName("model_id");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("serial_number");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("bicycles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Красный",
                            ModelId = 1,
                            SerialNumber = "SN-1001"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Чёрный",
                            ModelId = 2,
                            SerialNumber = "SN-1002"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Зелёный",
                            ModelId = 3,
                            SerialNumber = "SN-1003"
                        },
                        new
                        {
                            Id = 4,
                            Color = "Синий",
                            ModelId = 4,
                            SerialNumber = "SN-1004"
                        },
                        new
                        {
                            Id = 5,
                            Color = "Белый",
                            ModelId = 5,
                            SerialNumber = "SN-1005"
                        },
                        new
                        {
                            Id = 6,
                            Color = "Красный",
                            ModelId = 6,
                            SerialNumber = "SN-1006"
                        },
                        new
                        {
                            Id = 7,
                            Color = "Чёрный",
                            ModelId = 7,
                            SerialNumber = "SN-1007"
                        },
                        new
                        {
                            Id = 8,
                            Color = "Серый",
                            ModelId = 8,
                            SerialNumber = "SN-1008"
                        },
                        new
                        {
                            Id = 9,
                            Color = "Оранжевый",
                            ModelId = 9,
                            SerialNumber = "SN-1009"
                        },
                        new
                        {
                            Id = 10,
                            Color = "Жёлтый",
                            ModelId = 10,
                            SerialNumber = "SN-1010"
                        },
                        new
                        {
                            Id = 11,
                            Color = "Коричневый",
                            ModelId = 11,
                            SerialNumber = "SN-1011"
                        },
                        new
                        {
                            Id = 12,
                            Color = "Бирюзовый",
                            ModelId = 12,
                            SerialNumber = "SN-1012"
                        });
                });

            modelBuilder.Entity("BicycleRental.Domain.Models.BicycleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("BrakeType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("brake_type");

                    b.Property<double?>("MaxPassengerWeightKg")
                        .HasColumnType("double")
                        .HasColumnName("max_passenger_weight_kg");

                    b.Property<int?>("ModelYear")
                        .HasColumnType("int")
                        .HasColumnName("model_year");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price_per_hour");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("double")
                        .HasColumnName("weight_kg");

                    b.Property<double?>("WheelSizeInInches")
                        .HasColumnType("double")
                        .HasColumnName("wheel_size_in_inches");

                    b.HasKey("Id");

                    b.ToTable("bicycle_models", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrakeType = "Disc",
                            MaxPassengerWeightKg = 100.0,
                            ModelYear = 2024,
                            Name = "SportPro 1000",
                            PricePerHour = 7.50m,
                            Type = 4,
                            WeightKg = 8.5,
                            WheelSizeInInches = 28.0
                        },
                        new
                        {
                            Id = 2,
                            BrakeType = "Disc",
                            MaxPassengerWeightKg = 95.0,
                            ModelYear = 2023,
                            Name = "SpeedX Race",
                            PricePerHour = 9.00m,
                            Type = 4,
                            WeightKg = 7.7999999999999998,
                            WheelSizeInInches = 28.0
                        },
                        new
                        {
                            Id = 3,
                            BrakeType = "Disc",
                            MaxPassengerWeightKg = 120.0,
                            ModelYear = 2022,
                            Name = "MountainMax",
                            PricePerHour = 5.50m,
                            Type = 1,
                            WeightKg = 14.0,
                            WheelSizeInInches = 27.0
                        },
                        new
                        {
                            Id = 4,
                            BrakeType = "V-Brake",
                            MaxPassengerWeightKg = 110.0,
                            ModelYear = 2021,
                            Name = "CityComfort",
                            PricePerHour = 3.50m,
                            Type = 0,
                            WeightKg = 12.5,
                            WheelSizeInInches = 26.0
                        },
                        new
                        {
                            Id = 5,
                            BrakeType = "Disc",
                            MaxPassengerWeightKg = 120.0,
                            ModelYear = 2024,
                            Name = "EcoRide E1",
                            PricePerHour = 12.00m,
                            Type = 3,
                            WeightKg = 22.0,
                            WheelSizeInInches = 26.0
                        },
                        new
                        {
                            Id = 6,
                            BrakeType = "Caliper",
                            MaxPassengerWeightKg = 90.0,
                            ModelYear = 2020,
                            Name = "RoadMaster",
                            PricePerHour = 6.00m,
                            Type = 2,
                            WeightKg = 8.9000000000000004,
                            WheelSizeInInches = 28.0
                        },
                        new
                        {
                            Id = 7,
                            BrakeType = "Disc",
                            MaxPassengerWeightKg = 115.0,
                            ModelYear = 2023,
                            Name = "TrailRunner",
                            PricePerHour = 5.75m,
                            Type = 1,
                            WeightKg = 13.0,
                            WheelSizeInInches = 27.0
                        },
                        new
                        {
                            Id = 8,
                            BrakeType = "V-Brake",
                            MaxPassengerWeightKg = 105.0,
                            ModelYear = 2022,
                            Name = "UrbanLite",
                            PricePerHour = 3.00m,
                            Type = 0,
                            WeightKg = 11.0,
                            WheelSizeInInches = 26.0
                        },
                        new
                        {
                            Id = 9,
                            BrakeType = "Caliper",
                            MaxPassengerWeightKg = 95.0,
                            ModelYear = 2025,
                            Name = "SprintElite",
                            PricePerHour = 8.50m,
                            Type = 2,
                            WeightKg = 7.5999999999999996,
                            WheelSizeInInches = 28.0
                        },
                        new
                        {
                            Id = 10,
                            BrakeType = "V-Brake",
                            MaxPassengerWeightKg = 120.0,
                            ModelYear = 2019,
                            Name = "ComfortCity",
                            PricePerHour = 2.50m,
                            Type = 0,
                            WeightKg = 13.5,
                            WheelSizeInInches = 26.0
                        },
                        new
                        {
                            Id = 11,
                            BrakeType = "Coaster",
                            MaxPassengerWeightKg = 100.0,
                            ModelYear = 2015,
                            Name = "VintageTour",
                            PricePerHour = 1.50m,
                            Type = 0,
                            WeightKg = 15.0,
                            WheelSizeInInches = 26.0
                        },
                        new
                        {
                            Id = 12,
                            BrakeType = "Disc",
                            MaxPassengerWeightKg = 110.0,
                            ModelYear = 2018,
                            Name = "TestModelX",
                            PricePerHour = 4.00m,
                            Type = 1,
                            WeightKg = 14.5,
                            WheelSizeInInches = 27.0
                        });
                });

            modelBuilder.Entity("BicycleRental.Domain.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BicycleId")
                        .HasColumnType("int")
                        .HasColumnName("bicycle_id");

                    b.Property<TimeSpan>("DurationHours")
                        .HasColumnType("time(6)")
                        .HasColumnName("duration_hours");

                    b.Property<int>("RenterId")
                        .HasColumnType("int")
                        .HasColumnName("renter_id");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_at");

                    b.HasKey("Id");

                    b.HasIndex("BicycleId");

                    b.HasIndex("RenterId");

                    b.ToTable("rentals", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BicycleId = 1,
                            DurationHours = new TimeSpan(0, 2, 30, 0, 0),
                            RenterId = 1,
                            StartAt = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BicycleId = 2,
                            DurationHours = new TimeSpan(0, 1, 0, 0, 0),
                            RenterId = 1,
                            StartAt = new DateTime(2025, 1, 12, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BicycleId = 1,
                            DurationHours = new TimeSpan(0, 3, 0, 0, 0),
                            RenterId = 1,
                            StartAt = new DateTime(2025, 2, 3, 16, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            BicycleId = 3,
                            DurationHours = new TimeSpan(0, 1, 30, 0, 0),
                            RenterId = 2,
                            StartAt = new DateTime(2025, 2, 5, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            BicycleId = 4,
                            DurationHours = new TimeSpan(0, 4, 0, 0, 0),
                            RenterId = 3,
                            StartAt = new DateTime(2025, 2, 7, 11, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            BicycleId = 5,
                            DurationHours = new TimeSpan(0, 0, 30, 0, 0),
                            RenterId = 4,
                            StartAt = new DateTime(2025, 2, 10, 9, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            BicycleId = 6,
                            DurationHours = new TimeSpan(0, 6, 0, 0, 0),
                            RenterId = 5,
                            StartAt = new DateTime(2025, 3, 1, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            BicycleId = 7,
                            DurationHours = new TimeSpan(0, 2, 0, 0, 0),
                            RenterId = 6,
                            StartAt = new DateTime(2025, 3, 4, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            BicycleId = 8,
                            DurationHours = new TimeSpan(0, 12, 0, 0, 0),
                            RenterId = 7,
                            StartAt = new DateTime(2025, 3, 10, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            BicycleId = 9,
                            DurationHours = new TimeSpan(0, 8, 0, 0, 0),
                            RenterId = 8,
                            StartAt = new DateTime(2025, 3, 15, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            BicycleId = 2,
                            DurationHours = new TimeSpan(0, 3, 30, 0, 0),
                            RenterId = 9,
                            StartAt = new DateTime(2025, 4, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            BicycleId = 3,
                            DurationHours = new TimeSpan(0, 1, 0, 0, 0),
                            RenterId = 10,
                            StartAt = new DateTime(2025, 4, 3, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            BicycleId = 5,
                            DurationHours = new TimeSpan(1, 0, 0, 0, 0),
                            RenterId = 11,
                            StartAt = new DateTime(2025, 4, 10, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            BicycleId = 9,
                            DurationHours = new TimeSpan(0, 0, 45, 0, 0),
                            RenterId = 1,
                            StartAt = new DateTime(2025, 4, 12, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BicycleRental.Domain.Models.Renter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("last_name");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("patronymic");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.ToTable("renters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Александр",
                            LastName = "Александров",
                            Patronymic = "Александрович",
                            Phone = "+7-900-000-0001"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Пётр",
                            LastName = "Петров",
                            Patronymic = "Петрович",
                            Phone = "+7-900-000-0002"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Сергей",
                            LastName = "Сергеев",
                            Patronymic = "Сергеевич",
                            Phone = "+7-900-000-0003"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Ольга",
                            LastName = "Ольгина",
                            Patronymic = "Олеговна",
                            Phone = "+7-900-000-0004"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Даниил",
                            LastName = "Даниилов",
                            Patronymic = "Даниилович",
                            Phone = "+7-900-000-0005"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Евгений",
                            LastName = "Онегин",
                            Phone = "+7-900-000-0006"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Маркус",
                            LastName = "Аврелиус",
                            Patronymic = "Антонинус",
                            Phone = "+7-900-000-0007"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Фёдор",
                            LastName = "Фёдоров",
                            Patronymic = "Фёдорович",
                            Phone = "+7-900-000-0008"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Алексей",
                            LastName = "Смирнов",
                            Phone = "+7-900-000-0009"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Алексей",
                            LastName = "Алексеев",
                            Patronymic = "Алексеевич",
                            Phone = "+7-900-000-0010"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Кирилл",
                            LastName = "Кириллов",
                            Patronymic = "Кириллович",
                            Phone = "+7-900-000-0011"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Михаил",
                            LastName = "Михаилов",
                            Patronymic = "Михайлович",
                            Phone = "+7-900-000-0012"
                        });
                });

            modelBuilder.Entity("BicycleRental.Domain.Models.Bicycle", b =>
                {
                    b.HasOne("BicycleRental.Domain.Models.BicycleModel", null)
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BicycleRental.Domain.Models.Rental", b =>
                {
                    b.HasOne("BicycleRental.Domain.Models.Bicycle", null)
                        .WithMany()
                        .HasForeignKey("BicycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BicycleRental.Domain.Models.Renter", null)
                        .WithMany()
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
