<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Program.cs~RF39401120.TMP" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BicycleRental.Api.Contracts\BicycleRental.Api.Contracts.csproj" />
    <ProjectReference Include="..\BicycleRental.Application\BicycleRental.Application.csproj" />
    <ProjectReference Include="..\BicycleRental.Domain\BicycleRental.Domain.csproj" />
    <ProjectReference Include="..\BicycleRental.Infrastructure\BicycleRental.Infrastructure.csproj" />
  </ItemGroup>

</Project>
