<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="15.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BicycleRental.Api.Contracts\BicycleRental.Api.Contracts.csproj" />
		<ProjectReference Include="..\BicycleRental.Domain\BicycleRental.Domain.csproj" />
	</ItemGroup>
</Project>